### ISSUE TITLE
HetConv or Group conv ??

### ISSUE THREAD

**Issue by qiulinzhang** [irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions#1]
Thanks for your code, I read them and found that you use group conv on all the channels, not on M/p channel, so flops reduction mainly due to Group Conv, rather than less 3x3 kernels. 
if my understanding is not right, could you please show me some explanations?

**Comment by irvinxav** [comment]
group conv with groups=p perform convolution on M/p channels and the corresponding pointwise convolution result is added to perform HetConv operation
