### ISSUE TITLE
FLOPs 

### ISSUE THREAD

**Issue by qiulinzhang** [irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions#2]
Thanks for your code, I have a question about how FLOPs are Calculated? I use `https://github.com/Lyken17/pytorch-OpCounter` to count FLOPs？find 349.51M, 30M more than 313.74M in your code and original paper.

**Comment by vkverma01** [comment]
To make the implementation easy there is zero masking on line no. 172-176. 
That flops are not calculated in the paper. 
This is not exact implementation but easiest one.
The theoratical flops are reported in the paper, and it is calculated by ignoring zeros.
